In [3]:
import torch

In [13]:
t=torch.FloatTensor([[1,2,3],
                    [4,5,6],
                    [7,8,9],
                    [10,11,12]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [21]:
print(t.dim())
print(t.size())
print(t.shape)
print(t[:3])
print(t[:,:-1])

2
torch.Size([4, 3])
torch.Size([4, 3])
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


In [23]:
m1=torch.FloatTensor([[3,3]])
m2=torch.FloatTensor([[2],[2]])

print(m1+m2)

tensor([[5., 5.],
        [5., 5.]])


In [25]:
print(m1*m2)
print(m1.matmul(m2))

tensor([[6., 6.],
        [6., 6.]])
tensor([[12.]])


In [31]:
print(t)
print()
print(t.max(dim=1))
print()
print(t.argmax(dim=0))
print()
print(t.argmax(dim=1))

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

torch.return_types.max(
values=tensor([ 3.,  6.,  9., 12.]),
indices=tensor([2, 2, 2, 2]))

tensor([3, 3, 3])

tensor([2, 2, 2, 2])


In [34]:
print(t.view(3,-1))

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [36]:
t=torch.FloatTensor([[1],[2],[3]])

print(t)

tensor([[1.],
        [2.],
        [3.]])


In [49]:
print(t)
print(t.shape,'\n')
t2=t.squeeze()
print(t2)
print(t2.shape,'\n')
t3=t2.unsqueeze(0)
print(t3)
print(t3.shape,'\n')
t4=t2.unsqueeze(1)
print(t4)
print(t4.shape,'\n')

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1]) 

tensor([1., 2., 3.])
torch.Size([3]) 

tensor([[1., 2., 3.]])
torch.Size([1, 3]) 

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1]) 



In [51]:
l=torch.LongTensor([1,2,3,4])
print(l)
print(l.float())

tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])


In [53]:
b=torch.ByteTensor([True,False,False,True])
print(b)
print(b.long())
print(b.float())

tensor([1, 0, 0, 1], dtype=torch.uint8)
tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


In [55]:
x=torch.FloatTensor([[1,2],[3,4]])
y=torch.FloatTensor([[5,6],[7,8]])

print(torch.cat([x,y],dim=0))
print(torch.cat([x,y],dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [59]:
x=torch.FloatTensor([1,4])
y=torch.FloatTensor([2,5])
z=torch.FloatTensor([3,6])

print(torch.stack([x,y,z]))
print(torch.stack([x,y,z],dim=1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [60]:
x=torch.FloatTensor([[1,2,3],[4,5,6]])
print(x)

print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [61]:
z=torch.zeros([3,4])
print(z)

o=torch.ones([2,6])
print(o)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])


In [64]:
x=torch.FloatTensor([[1,2],[3,4]])

print(x.mul(2.))
print(x)

print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


In [66]:
y=x.matmul(torch.FloatTensor([[2],[4]]))
print(x)
print(y)

tensor([[2., 4.],
        [6., 8.]])
tensor([[20.],
        [44.]])
